FROM --platform=${BUILDPLATFORM} ghcr.io/darkness4/fc2-live-dl-go:latest-darwin-base AS builder

WORKDIR /work
COPY go.mod go.sum ./
RUN go mod download

COPY . .

ARG TARGETARCH
ENV OSXCROSS_PKG_CONFIG_USE_NATIVE_VARIABLES=1
ENV PKG_CONFIG_PATH=/osxcross/lib/pkgconfig:/lib/pkgconfig

ARG VERSION=dev

RUN if [ "${TARGETARCH}" = "amd64" ]; then \
  export CC="/osxcross/bin/x86_64-apple-darwin25.1-clang"; \
  export CXX="/osxcross/bin/x86_64-apple-darwin25.1-clang++-stdc++"; \
  export PKG_CONFIG="/osxcross/bin/x86_64-apple-darwin25.1-pkg-config"; \
  export AR="/osxcross/bin/x86_64-apple-darwin25.1-ar"; \
  export NM="/osxcross/bin/x86_64-apple-darwin25.1-nm"; \
  export RANLIB="/osxcross/bin/x86_64-apple-darwin25.1-ranlib"; \
  export PKG_CONFIG_PATH="/osxcross/ffmpeg-x86_64/lib/pkgconfig:${PKG_CONFIG_PATH}"; \
  elif [ "${TARGETARCH}" = "arm64" ]; then \
  export CC="/osxcross/bin/aarch64-apple-darwin25.1-clang"; \
  export CXX="/osxcross/bin/aarch64-apple-darwin25.1-clang++-stdc++"; \
  export PKG_CONFIG="/osxcross/bin/aarch64-apple-darwin25.1-pkg-config"; \
  export AR="/osxcross/bin/aarch64-apple-darwin25.1-ar"; \
  export NM="/osxcross/bin/aarch64-apple-darwin25.1-nm"; \
  export RANLIB="/osxcross/bin/aarch64-apple-darwin25.1-ranlib"; \
  export PKG_CONFIG_PATH="/osxcross/ffmpeg-aarch64/lib/pkgconfig:${PKG_CONFIG_PATH}"; \
  fi; \
  GOOS=darwin GOARCH=${TARGETARCH} make bin/fc2-live-dl-go-darwin VERSION=${VERSION}

# Helper container to copy binaries outside the container using podman/buildx export. Unused in production.
FROM scratch AS export

ARG TARGETARCH
COPY --from=builder /work/bin/fc2-live-dl-go-darwin /fc2-live-dl-go-darwin-${TARGETARCH}
