FROM ghcr.io/darkness4/fc2-live-dl-go:latest-static-base as builder

WORKDIR /work
COPY go.mod go.sum ./
RUN go mod download

ARG TARGETOS TARGETARCH
COPY . .

RUN CGO_ENABLED=1 GOOS=$TARGETOS GOARCH=$TARGETARCH make bin/fc2-live-dl-go-static

FROM scratch

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=builder /work/bin/fc2-live-dl-go-static /fc2-live-dl-go

ENTRYPOINT [ "/fc2-live-dl-go" ]
