FROM ghcr.io/darkness4/fc2-live-dl-go:latest-static-windows-base AS builder

WORKDIR /work
COPY go.mod go.sum ./
RUN go mod download

COPY . .

ARG VERSION=dev

RUN make bin/fc2-live-dl-go-static.exe VERSION=${VERSION}

# Helper container to copy binaries outside the container using podman/buildx export. Unused in production.
FROM scratch AS export

ARG TARGETARCH
COPY --from=builder /work/bin/fc2-live-dl-go-static.exe /fc2-live-dl-go-windows-${TARGETARCH}.exe
