# This Dockerfile is used to run valgrind (mem leaks) tests.

FROM alpine:3.21

RUN apk add --no-cache \
  ffmpeg-dev \
  ffmpeg-libavformat \
  ffmpeg-libavcodec \
  ffmpeg-libavutil \
  gcc \
  musl-dev \
  make \
  valgrind
