FROM ghcr.io/darkness4/fc2-live-dl-go:latest-static-windows-base

WORKDIR /work
COPY go.mod go.sum ./
RUN go mod download

COPY . .

ARG VERSION=dev

RUN make bin/fc2-live-dl-go-static.exe VERSION=${VERSION}
