{
 "title": "FC2 Live DL Go",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(watcher_state,job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "State of workers",
   "type": "state-timeline",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "watcher_state{job=~\"$job\"} != 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "State of workers",
   "type": "heatmap",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (state) (watcher_state{job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Go Profiling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(go_goroutines{job=~\"$job\"})",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "Alloc",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(go_memstats_alloc_bytes{job=~\"$job\"})",
     "legendFormat": "Actual"
    }
   ]
  },
  {
   "title": "OS Threads",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(go_threads{job=~\"$job\"})",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "Number of allocated objects.",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(go_memstats_heap_objects{job=~\"$job\"})",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "Heap",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(go_memstats_heap_alloc_bytes{job=~\"$job\"})",
     "legendFormat": "Alloc & In Use"
    },
    {
     "expr": "sum(go_memstats_heap_idle_bytes{job=~\"$job\"})",
     "legendFormat": "Idle"
    },
    {
     "expr": "sum(go_memstats_heap_inuse_bytes{job=~\"$job\"})",
     "legendFormat": "In Use"
    },
    {
     "expr": "sum(go_memstats_heap_released_bytes{job=~\"$job\"})",
     "legendFormat": "Released"
    },
    {
     "expr": "sum(go_memstats_heap_sys_bytes{job=~\"$job\"})",
     "legendFormat": "Sys"
    }
   ]
  },
  {
   "title": "Total number of mallocs/frees.",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "sum(rate(go_memstats_mallocs_total{job=~\"$job\"}[5m]))",
     "legendFormat": "Mallocs"
    },
    {
     "expr": "sum(rate(go_memstats_frees_total{job=~\"$job\"}[5m]))",
     "legendFormat": "Frees"
    },
    {
     "expr": "sum(rate(go_memstats_lookups_total{job=~\"$job\"}[5m]))",
     "legendFormat": "Lookups"
    }
   ]
  },
  { "title": "HTTP Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Query duration 0.95 quantile",
   "type": "timeseries",
   "gridPos": { "h": 24, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(http_client_duration_milliseconds_bucket{job=~\"$job\"}) by (le, net_peer_name, http_method, http_status_code))",
     "legendFormat": "{{http_method}} {{net_peer_name}} {{http_status_code}}"
    }
   ]
  },
  {
   "title": "Request sizes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(http_client_request_size_bytes_total{job=~\"$job\"}[5m])) by (le, net_peer_name, http_method, http_status_code)",
     "legendFormat": "{{http_method}} {{net_peer_name}} {{http_status_code}}"
    }
   ]
  },
  {
   "title": "Response sizes",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "-sum(rate(http_client_response_size_bytes_total{job=~\"$job\"}[5m])) by (le, net_peer_name, http_method, http_status_code)",
     "legendFormat": "{{http_method}} {{net_peer_name}} {{http_status_code}}"
    }
   ]
  },
  { "title": "Download", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Runs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(downloads_runs_total{job=~\"$job\"})",
     "legendFormat": "Runs"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(downloads_errors_total{job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Initialization duration (s)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(downloads_init_time_seconds_bucket{job=~\"$job\"}[$__range])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Initialization duration 0.95 quantile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(downloads_init_time_seconds_bucket{job=~\"$job\"}) by (le))",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "Completion duration (s)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(downloads_time_to_complete_seconds_bucket{job=~\"$job\"}[$__range])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Completion duration 0.95 quantile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(downloads_time_to_complete_seconds_bucket{job=~\"$job\"}) by (le))",
     "legendFormat": "Value"
    }
   ]
  },
  { "title": "Concatenation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Runs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 82 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(concat_runs_total{job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 82 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(concat_errors_total{job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Completion duration (s)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 87 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(concat_completion_time_seconds_bucket{job=~\"$job\"}[$__range])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Completion duration 0.95 quantile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(concat_completion_time_seconds_bucket{job=~\"$job\"}) by (le))",
     "legendFormat": "Value"
    }
   ]
  },
  { "title": "Post-Processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "Runs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 95 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(post_processing_runs_total{job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 95 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(post_processing_errors_total{job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Completion duration (s)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 100 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(post_processing_completion_time_seconds_bucket{job=~\"$job\"}[$__range])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Completion duration 0.95 quantile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(post_processing_completion_time_seconds_bucket{job=~\"$job\"}) by (le))",
     "legendFormat": "Value"
    }
   ]
  },
  { "title": "Cleaner", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 } },
  {
   "title": "Runs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 108 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cleaner_runs_total{job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 108 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cleaner_errors_total{job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Files removed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 108 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cleaner_files_removed_total{job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time to clean (ms)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 113 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(cleaner_clean_time_milliseconds_bucket{job=~\"$job\"}[$__range])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Completion duration 0.95 quantile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(cleaner_clean_time_milliseconds_bucket{job=~\"$job\"}) by (le))",
     "legendFormat": "Value"
    }
   ]
  }
 ]
}