notifier:
  gotify:
    enabled: true
    endpoint: https://gotify.example.com
    token: 'random'

defaultParams:
  quality: 3Mbps
  latency: mid
  outFormat: /output/{{ .ChannelName }} {{ .Labels.EnglishName }}/{{ .Date }} {{ .Title }}.{{ .Ext }}
  waitForLive: true
  remux: false
  remuxFormat: mp4
  concat: true
  keepIntermediates: false
  scanDirectory: '/output'
  eligibleForCleaningAge: '48h'
  deleteCorrupted: true
  extractAudio: true

channels:
  '40740626':
    labels:
      EnglishName: Komae Nadeshiko
  '72364867':
    labels:
      EnglishName: Uno Sakura
  '81840800':
    labels:
      EnglishName: Ronomiya Hinagiku
  '91544481':
    labels:
      EnglishName: Necoma Karin
