apiVersion: v1
kind: ConfigMap
metadata:
  name: fc2-config
data:
  autofc2.yaml: |

    notifier:
      gotify:
        enabled: true
        endpoint: https://gotify.example.com
        token: 'random'

    defaultParams:
      quality: 3Mbps
      latency: mid
      outFormat: /output/{{ .ChannelName }} {{ .Labels.EnglishName }}/{{ .Date }} {{ .Title }}.{{ .Ext }}
      packetLossMax: 20
      writeChat: false
      writeInfoJson: false
      writeThumbnail: false
      waitForLive: true
      waitForQualityMaxTries: 10
      waitPollInterval: '10s'
      cookiesFile: ''
      remux: true
      remuxFormat: mp4
      concat: false
      keepIntermediates: false
      extractAudio: true
      labels: {}

    channels:
      '40740626':
        labels:
          EnglishName: Komae Nadeshiko
      '72364867':
        labels:
          EnglishName: Uno Sakura
      '81840800':
        labels:
          EnglishName: Ronomiya Hinagiku
      '91544481':
        labels:
          EnglishName: Necoma Karin
