apiVersion: v1
kind: ConfigMap
metadata:
  name: fc2-config
data:
  autofc2.yaml: |

    defaultParams:
      quality: 1.2Mbps
      latency: mid
      outFormat: /output/{{ .ChannelName }} {{ .Labels.EnglishName }}/{{ .Date }} {{ .Title }}.{{ .Ext }}
      packetLossMax: 20
      writeChat: false
      writeInfoJson: false
      writeThumbnail: false
      waitForLive: true
      waitForQualityMaxTries: 10
      waitPollInterval: '10s'
      cookiesFile: ''
      remux: true
      keepIntermediates: false
      extractAudio: true
      labels: {}

    channels:
      '40740626':
        labels:
          EnglishName: Komae Nadeshiko
      '72364867':
        labels:
          EnglishName: Uno Sakura
      '81840800':
        labels:
          EnglishName: Ronomiya Hinagiku
      '91544481':
        labels:
          EnglishName: Necoma Karin
      '90064799':
        labels:
          EnglishName: Necoma Karin
      '84683124':
        labels:
          EnglishName: Mia Owred
      '75399790':
        labels:
          EnglishName: Chris Hina
      '38539022':
        labels:
          EnglishName: Amagami Nico
      '64937358':
        labels:
          EnglishName: Fuwari Kira
      '27043183':
        labels:
          EnglishName: Nekoname Tuna
      '53306736':
        labels:
          EnglishName: Kurono Riku
      '8770876':
        labels:
          EnglishName: Chii Hoshimori
      '41958478':
        labels:
          EnglishName: Kimitsu Tenka
