apiVersion: apps/v1
kind: Deployment
metadata:
  name: fc2
  labels:
    app: fc2
spec:
  selector:
    matchLabels:
      app: fc2
  replicas: 1
  template:
    metadata:
      labels:
        app: fc2
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 2000
        fsGroup: 2000
        runAsNonRoot: true
      terminationGracePeriodSeconds: 30
      containers:
        - name: fc2
          image: ghcr.io/darkness4/fc2-live-dl-go:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 1000
            runAsGroup: 2000
            runAsNonRoot: true
            capabilities:
              drop: [ALL]
          args:
            - watch
            - -c
            - /config/autofc2.yaml
          ports:
            - name: http
              containerPort: 3000
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 3
            timeoutSeconds: 5
            httpGet:
              port: 3000
              path: /
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            httpGet:
              port: 3000
              path: /
          resources:
            requests:
              cpu: '250m'
              memory: 256Mi
            limits:
              memory: 1Gi
          volumeMounts:
            - mountPath: '/output'
              name: fc2-output-claim
            - mountPath: '/config'
              name: fc2-config
      volumes:
        - name: fc2-config
          configMap:
            name: fc2-config
            defaultMode: 0600
        - name: fc2-output
          persistentVolumeClaim:
            claimName: fc2-output-claim
